### PR TITLE
updated to version 1.36; Re-rendered with conda-build 3.17.8, conda-smithy 3.3.0, and conda-forge-pinning 2019.03.17; added license_file; fixed homepage; added error checking in build script.

### PR DESCRIPTION
**Pull request by notestaff**
updated to version 1.36; Re-rendered with conda-build 3.17.8, conda-smithy 3.3.0, and conda-forge-pinning 2019.03.17; added license_file; fixed homepage; added error checking in build script.

Checklist
* [X] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by notestaff** [comment]
@martindurant @mariusvniekerk please look this over when you have time

**Comment by martindurant** [comment]
Personally, I am a bit out of touch with this stack now, not sure I can be helpful

**Comment by notestaff** [comment]
@mariusvniekerk when you have time, could you look over this update?  thanks!

**Comment by mariusvniekerk** [comment]
Thanks

**Pull request merged**
